- name: Garante que o grupo "icecast2" exista
  ansible.builtin.group:
    name: icecast2
    state: present

- name: Adicionar o usuário icecast2
  ansible.builtin.user:
    name: "icecast2"
    group: "icecast2"

- name: Alterar as configurações do Icecast
  ansible.builtin.copy:
    src: etc/icecast2/rhythm.xml
    dest: /etc/icecast2/rhythm.xml
    owner: icecast2
    group: icecast2
    force: true
    mode: '0644'