server {
    listen 80;
    listen [::]:80;
    server_name psique.paxa.dev;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;

    ssl_certificate         /etc/letsencrypt/live/psique.paxa.dev/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/psique.paxa.dev/privkey.pem;

    server_name psique.paxa.dev;
    root /var/www/psique.paxa.dev;
    
    include conf.d/cache.conf;
    include conf.d/paxa-errors.conf;

    location / {
        try_files $uri $uri/ =404;
    }
}
