server {
    listen 80;
    listen [::]:80;

    listen 443 ssl;
    listen [::]:443 ssl;

    ssl_certificate         /etc/nginx/ssl/certificates/somdomato.com.crt;
    ssl_certificate_key     /etc/nginx/ssl/certificates/somdomato.com.key;

    proxy_intercept_errors on;

    server_name somdomato.com.br *.somdomato.com.br;    
    return 301 https://somdomato.com$request_uri;
}
