include conf.d/nuxt.map;

server {
    listen 80;
    listen [::]:80;
    server_name somdomato.com;
    return 301 https://somdomato.com$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    ssl_certificate         /etc/nginx/ssl/certificates/somdomato.com.crt;
    ssl_certificate_key     /etc/nginx/ssl/certificates/somdomato.com.key;

    server_name somdomato.com;
    root /var/www/somdomato/packages/site/dist;

    # This is a cache for SSL connections
    # ssl_session_cache shared:le_nginx_SSL:1m;
    # ssl_session_timeout 1440m;

    location /whatsapp { return 301 https://chat.whatsapp.com/FjJqPtI1keX5ZnsN9LdNT2; }
    location /facebook { return 301 https://facebook.com/somdomato; }
    location /twitter { return 301 https://twitter.com/radiosomdomato; }
    location /telegram { return 301 https://t.me/somdomato; }
    location /discord { return 301 https://discord.gg/vjDfCTmBpx; }

    include conf.d/error.conf;
    include conf.d/vite.conf;
    include conf.d/deny.conf;
}
