server {
    listen 80;
    listen [::]:80;
    server_name *.rhythm.place rhythm.place;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    ssl_certificate         /etc/letsencrypt/live/rhythm.place/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/rhythm.place/privkey.pem;

    server_name www.rhythm.place;
    return 301 https://rhythm.place$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    ssl_certificate         /etc/letsencrypt/live/rhythm.place/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/rhythm.place/privkey.pem;

    server_name rhythm.place *.rhythm.place;

    proxy_intercept_errors on;

    include conf.d/rtm-errors.conf;
    include conf.d/next.conf;
    include conf.d/deny.conf;
}