set -g allow-rename off
set -g set-titles-string '#{pane_title}'
set -g mouse on
setw -g xterm-keys on
set -g history-limit 30000
set -g base-index 1
set -g remain-on-exit on
setw -g remain-on-exit on

# Binds
bind K kill-server
bind k kill-session
bind x kill-pane
bind R source-file ~/.tmux-code.conf

unbind NPage
unbind PPage
bind -n PPage previous-window
bind -n NPage next-window

bind -n ^1 select-window -t 1

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'

set -g @catppuccin_flavour 'macchiato' # latte, frappe, macchiato, mocha
set -g @catppuccin_powerline_icons_theme_enabled on
set -g @catppuccin_l_left_separator ""
set -g @catppuccin_l_right_separator ""
set -g @catppuccin_r_left_separator ""
set -g @catppuccin_r_right_separator ""

source /usr/share/powerline/bindings/tmux/powerline.conf

run '~/.tmux/plugins/tpm/tpm'
