version: '3'

services:
  icecast2:
    container_name: rhythm-icecast2
    image: pltnk/icecast2
    ports:
      - "8000:8000"
    volumes:
      - ../files/etc/icecast2:/etc/icecast2
    restart: unless-stopped

  liquidsoap:
    container_name: rhythm-liquidsoap
    image: pltnk/liquidsoap
    volumes:
      - ../files/etc/liquidsoap/radio.liq:/etc/liquidsoap/script.liq
      - ../packages/api/songs:/music
      # - ../files/etc/liquidsoap/playlists:/playlists
    depends_on:
      - icecast2
    restart: unless-stopped

  # postgresql:
  #   container_name: postgresql
  #   image: postgres:14.0
  #   environment:
  #     POSTGRES_PASSWORD: yourpassword
  #     POSTGRES_USER: youruser
  #     POSTGRES_DB: yourdb
  #   # volumes:
  #   #   - ./data/postgres:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

volumes:
  # postgres_data:
  music_data:
  playlists_data:

