name: Vite Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy site via SSH with password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          source: "."
          target: ${{ secrets.PROJECT_PATH }}

  build:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Add Bun to PATH
        shell: bash
        run: |
          echo "/home/nginx/.bun/bin" >> $GITHUB_PATH

      - name: Install Vite using Bun
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            bash scripts/deploy.sh
